### ISSUE TITLE
Array and object support?

### ISSUE THREAD

**Issue by ethanhann** [RustJason/php-rapidjson#5]
Are there plans to add support for nested arrays and objects? When I try to decode JSON with them they evaluate to NULL.

**Comment by rustjson** [comment]
NESTED arrays and objects could be supported, but that would take any advantages of Rapidjson and that's why I did not keep doing.

**Comment by ethanhann** [comment]
Does Rapidjson not work well with nested arrays and objects?

**Comment by rustjson** [comment]
No, It does not
